=== Amareshwari/incubator-lens/grill-api/src/main/resources/cube-0.1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="uri:grill:cube:0.1"
           xmlns="uri:grill:cube:0.1"
           xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.1">
    <xs:annotation>
        <xs:appinfo>
            <jaxb:schemaBindings>
                <jaxb:package name="com.inmobi.grill.metastore.model"/>
            </jaxb:schemaBindings>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="x_cube" type="x_cube">
    </xs:element>
    <xs:complexType name="x_cube">
        <xs:annotation>
            <xs:documentation>
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_measures" name="measures"/>
            <xs:element type="x_dimensions" name="dimensions"/>
            <xs:element type="x_properties" name="properties" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="description"/>
    </xs:complexType>
    <xs:complexType name="x_property">
        <xs:annotation>
            <xs:documentation>
                A key-value pair, which are propagated to the cube.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="value" use="required"/>
    </xs:complexType>
    <xs:complexType name="x_properties">
        <xs:annotation>
            <xs:documentation>
                A list of property elements.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_property" name="property" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="x_measure">
        <xs:annotation>
            <xs:documentation>
                A cube measure.
            </xs:documentation>
        </xs:annotation>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="defaultaggr" />
        <xs:attribute type="xs:string" name="formatString" />
        <xs:attribute type="xs:dateTime" name="starttime" />
        <xs:attribute type="xs:dateTime" name="endtime" />
        <xs:attribute type="xs:double" name="cost" />
        <xs:attribute type="xs:string" name="expr" />
    </xs:complexType>
    <xs:complexType name="x_measures">
        <xs:annotation>
            <xs:documentation>
                Set of measures.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_measure" name="measure" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="x_dimension">
        <xs:annotation>
            <xs:documentation>
                A cube dimension.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
          <xs:element type="x_tablereferences" name="references" />
        </xs:sequence>
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:dateTime" name="starttime" />
        <xs:attribute type="xs:dateTime" name="endtime" />
        <xs:attribute type="xs:double" name="cost" />
        <xs:attribute type="xs:string" name="expr" />        
    </xs:complexType>
    <xs:complexType name="x_tablereference">
        <xs:attribute type="xs:string" name="desttable" use="required"/>
        <xs:attribute type="xs:string" name="destcolumn" use="required"/>
    </xs:complexType>
    <xs:complexType name="x_tablereferences">
        <xs:sequence>
            <xs:element type="x_tablereference" name="tablereference" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
 
    <xs:complexType name="x_dimensions">
        <xs:annotation>
            <xs:documentation>
                Set of dimensions.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element type="x_dimension" name="dimension" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Amareshwari/incubator-lens/grill-examples/src/main/resources/sample-cube.xml
<?xml version="1.0" encoding="UTF-8"?>
<x_cube name="sample_cube" xmlns="uri:grill:cube:0.1"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="uri:grill:cube:0.1 cube-0.1.xsd ">
  <measures>
    <measures name="measure1" type="bigint"/>
    <measures name="measure2" type="int" default_aggr="SUM"/>
    <measures name="measure3" type="float" default_aggr="MAX" start_time='2013-12-12-00:00'/>
    <measures name="measure4" type="double" default_aggr="MIN"/>
    <measures name="expr_msr5" type="double" expr="measure1 + measure2" />
  </measures>
  <dimensions>
    <dimensions name="dim1" type="int"/>
    <dimensions name="dim2" type="int" start_time='2013-12-01-00:00'/>
    <dimensions name="dim3" type="int">
      <references>
        <table_references dest_table="dim_table" dest_column="id"/>
      </references>
    </dimensions>
  </dimensions>
  <properties>
  <property name="sample_cube.prop" value="sample" />
  </properties>
</x_cube>
